-- This script was generated by Hydroxide

local oh1 = game:GetService("Workspace")["3xjn"]
local oh2 = 18
game:GetService("Workspace").CommunicationRelays.Character.AgeChange:InvokeServer(oh1, oh2)

-- This script was generated by Hydroxide

local oh1 = { { true, true, true }, { true, true, true }, { true, true, true }, { true, true, true }, { true, true, true }, { true, true, true }, { true, true, true }, { true, true, true }, { true, true, true }, { true, true, true }, { true, true, true }, { true, true, true }, { true, true, true }, { true, true, true }, { true, true, true } }
local oh2 = game:GetService("Workspace").Property["Antine Villa"]
game:GetService("Workspace").CommunicationRelays.House.SetPermissions:FireServer(oh1, oh2)

-- This script was generated by Hydroxide

local oh1 = "Line Cooks"
game:GetService("Workspace").CommunicationRelays.Interaction.TeamChange:FireServer(oh1)

-- This script was generated by Hydroxide

local oh1 = "CharacterName"
local oh2 = "Jake"
game:GetService("Workspace").CommunicationRelays.Character.NamePlateUpdate:FireServer(oh1, oh2)

-- This script was generated by Hydroxide

local oh1 = -220
game:GetService("Players")["3xjn"].ChangeMoney:Fire(oh1)


-- This script was generated by Hydroxide

local oh1 = game:GetService("ReplicatedStorage").Kiddos.Colin
local oh2 = game:GetService("Workspace").Cars.Schoolbus
game:GetService("Workspace").CommunicationRelays.Work.AddStudentToBus:InvokeServer(oh1, oh2)

-- DROP KIDS OFF SCRIPT
for _, students in pairs(workspace.Cars.Schoolbus:GetDescendants()) do
	if students.ClassName == "ObjectValue" and students.Value then
		local oh1 = students.Value.Name
		local oh2 = game:GetService("Workspace").Cars.Schoolbus
		game:GetService("Workspace").CommunicationRelays.Work.RemoveStudentFromBus:InvokeServer(oh1, oh2)
		print("Dropping off " .. oh1)
	end
end